const countries = [
  {
    name: 'Albania',
    capital: 'Tirana',
    currency: 'ALL',
    currencySymbol: 'L',
    population: 2877797,
    continent: 'Europe',
  },
  {
    name: 'Andorra',
    capital: 'Andorra la Vella',
    currency: 'EUR',
    currencySymbol: '€',
    population: 77265,
    continent: 'Europe',
  },
  {
    name: 'Armenia',
    capital: 'Yerevan',
    currency: 'AMD',
    currencySymbol: '֏',
    population: 2963243,
    continent: 'Europe',
  },
  {
    name: 'Austria',
    capital: 'Vienna',
    currency: 'EUR',
    currencySymbol: '€',
    population: 8917205,
    continent: 'Europe',
  },
  {
    name: 'Azerbaijan',
    capital: 'Baku',
    currency: 'AZN',
    currencySymbol: '₼',
    population: 10139177,
    continent: 'Europe',
  },
  {
    name: 'Belarus',
    capital: 'Minsk',
    currency: 'BYN',
    currencySymbol: 'Br',
    population: 9449323,
    continent: 'Europe',
  },
  {
    name: 'Belgium',
    capital: 'Brussels',
    currency: 'EUR',
    currencySymbol: '€',
    population: 11555997,
    continent: 'Europe',
  },
  {
    name: 'Bosnia and Herzegovina',
    capital: 'Sarajevo',
    currency: 'BAM',
    currencySymbol: 'KM',
    population: 3280815,
    continent: 'Europe',
  },
  {
    name: 'Bulgaria',
    capital: 'Sofia',
    currency: 'BGN',
    currencySymbol: 'лв',
    population: 6948445,
    continent: 'Europe',
  },
  {
    name: 'Croatia',
    capital: 'Zagreb',
    currency: 'HRK',
    currencySymbol: 'kn',
    population: 4047200,
    continent: 'Europe',
  },
  {
    name: 'Cyprus',
    capital: 'Nicosia',
    currency: 'EUR',
    currencySymbol: '€',
    population: 1207359,
    continent: 'Europe',
  },
  {
    name: 'Czech Republic',
    capital: 'Prague',
    currency: 'CZK',
    currencySymbol: 'Kč',
    population: 10708981,
    continent: 'Europe',
  },
  {
    name: 'Denmark',
    capital: 'Copenhagen',
    currency: 'DKK',
    currencySymbol: 'kr',
    population: 5831404,
    continent: 'Europe',
  },
  {
    name: 'Estonia',
    capital: 'Tallinn',
    currency: 'EUR',
    currencySymbol: '€',
    population: 1326535,
    continent: 'Europe',
  },
  {
    name: 'Finland',
    capital: 'Helsinki',
    currency: 'EUR',
    currencySymbol: '€',
    population: 5525292,
    continent: 'Europe',
  },
  {
    name: 'France',
    capital: 'Paris',
    currency: 'EUR',
    currencySymbol: '€',
    population: 67391582,
    continent: 'Europe',
  },
  {
    name: 'Georgia',
    capital: 'Tbilisi',
    currency: 'GEL',
    currencySymbol: '₾',
    population: 3716858,
    continent: 'Europe',
  },
  {
    name: 'Germany',
    capital: 'Berlin',
    currency: 'EUR',
    currencySymbol: '€',
    population: 83166711,
    continent: 'Europe',
  },
  {
    name: 'Greece',
    capital: 'Athens',
    currency: 'EUR',
    currencySymbol: '€',
    population: 10423054,
    continent: 'Europe',
  },
  {
    name: 'Hungary',
    capital: 'Budapest',
    currency: 'HUF',
    currencySymbol: 'Ft',
    population: 9749763,
    continent: 'Europe',
  },
  {
    name: 'Iceland',
    capital: 'Reykjavik',
    currency: 'ISK',
    currencySymbol: 'kr',
    population: 366425,
    continent: 'Europe',
  },
  {
    name: 'Ireland',
    capital: 'Dublin',
    currency: 'EUR',
    currencySymbol: '€',
    population: 4994724,
    continent: 'Europe',
  },
  {
    name: 'Italy',
    capital: 'Rome',
    currency: 'EUR',
    currencySymbol: '€',
    population: 59554023,
    continent: 'Europe',
  },
  {
    name: 'Kazakhstan',
    capital: 'Nur-Sultan',
    currency: 'KZT',
    currencySymbol: '₸',
    population: 18754440,
    continent: 'Europe',
  },
  {
    name: 'Kosovo',
    capital: 'Pristina',
    currency: 'EUR',
    currencySymbol: '€',
    population: 1831000,
    continent: 'Europe',
  },
  {
    name: 'Latvia',
    capital: 'Riga',
    currency: 'EUR',
    currencySymbol: '€',
    population: 1907675,
    continent: 'Europe',
  },
  {
    name: 'Liechtenstein',
    capital: 'Vaduz',
    currency: 'CHF',
    currencySymbol: 'Fr',
    population: 38749,
    continent: 'Europe',
  },
  {
    name: 'Lithuania',
    capital: 'Vilnius',
    currency: 'EUR',
    currencySymbol: '€',
    population: 2794700,
    continent: 'Europe',
  },
  {
    name: 'Luxembourg',
    capital: 'Luxembourg City',
    currency: 'EUR',
    currencySymbol: '€',
    population: 634814,
    continent: 'Europe',
  },
  {
    name: 'Malta',
    capital: 'Valletta',
    currency: 'EUR',
    currencySymbol: '€',
    population: 514564,
    continent: 'Europe',
  },
  {
    name: 'Moldova',
    capital: 'Chișinău',
    currency: 'MDL',
    currencySymbol: 'L',
    population: 2657637,
    continent: 'Europe',
  },
  {
    name: 'Monaco',
    capital: 'Monaco',
    currency: 'EUR',
    currencySymbol: '€',
    population: 39242,
    continent: 'Europe',
  },
  {
    name: 'Montenegro',
    capital: 'Podgorica',
    currency: 'EUR',
    currencySymbol: '€',
    population: 622359,
    continent: 'Europe',
  },
  {
    name: 'Netherlands',
    capital: 'Amsterdam',
    currency: 'EUR',
    currencySymbol: '€',
    population: 17441139,
    continent: 'Europe',
  },
  {
    name: 'North Macedonia',
    capital: 'Skopje',
    currency: 'MKD',
    currencySymbol: 'ден',
    population: 2077132,
    continent: 'Europe',
  },
  {
    name: 'Norway',
    capital: 'Oslo',
    currency: 'NOK',
    currencySymbol: 'kr',
    population: 5379475,
    continent: 'Europe',
  },
  {
    name: 'Poland',
    capital: 'Warsaw',
    currency: 'PLN',
    currencySymbol: 'zł',
    population: 38386000,
    continent: 'Europe',
  },
  {
    name: 'Portugal',
    capital: 'Lisbon',
    currency: 'EUR',
    currencySymbol: '€',
    population: 10295909,
    continent: 'Europe',
  },
  {
    name: 'Romania',
    capital: 'Bucharest',
    currency: 'RON',
    currencySymbol: 'lei',
    population: 19237691,
    continent: 'Europe',
  },
  {
    name: 'Russia',
    capital: 'Moscow',
    currency: 'RUB',
    currencySymbol: '₽',
    population: 145912025,
    continent: 'Europe',
  },
  {
    name: 'San Marino',
    capital: 'San Marino',
    currency: 'EUR',
    currencySymbol: '€',
    population: 33931,
    continent: 'Europe',
  },
  {
    name: 'Serbia',
    capital: 'Belgrade',
    currency: 'RSD',
    currencySymbol: 'дин',
    population: 6930564,
    continent: 'Europe',
  },
  {
    name: 'Slovakia',
    capital: 'Bratislava',
    currency: 'EUR',
    currencySymbol: '€',
    population: 5456362,
    continent: 'Europe',
  },
  {
    name: 'Slovenia',
    capital: 'Ljubljana',
    currency: 'EUR',
    currencySymbol: '€',
    population: 2100126,
    continent: 'Europe',
  },
  {
    name: 'Spain',
    capital: 'Madrid',
    currency: 'EUR',
    currencySymbol: '€',
    population: 47351567,
    continent: 'Europe',
  },
  {
    name: 'Sweden',
    capital: 'Stockholm',
    currency: 'SEK',
    currencySymbol: 'kr',
    population: 10379295,
    continent: 'Europe',
  },
  {
    name: 'Switzerland',
    capital: 'Bern',
    currency: 'CHF',
    currencySymbol: 'Fr',
    population: 8665615,
    continent: 'Europe',
  },
  {
    name: 'Turkey',
    capital: 'Ankara',
    currency: 'TRY',
    currencySymbol: '₺',
    population: 84680273,
    continent: 'Europe',
  },
  {
    name: 'Ukraine',
    capital: 'Kyiv',
    currency: 'UAH',
    currencySymbol: '₴',
    population: 41660982,
    continent: 'Europe',
  },
  {
    name: 'United Kingdom',
    capital: 'London',
    currency: 'GBP',
    currencySymbol: '£',
    population: 67000000,
    continent: 'Europe',
  },
  {
    name: 'Vatican City',
    capital: 'Vatican City',
    currency: 'EUR',
    currencySymbol: '€',
    population: 800,
    continent: 'Europe',
  },

  {
    name: 'Algeria',
    capital: 'Algiers',
    currency: 'DZD',
    currencySymbol: 'د.ج',
    population: 43851044,
    continent: 'Africa',
  },
  {
    name: 'Angola',
    capital: 'Luanda',
    currency: 'AOA',
    currencySymbol: 'Kz',
    population: 32866272,
    continent: 'Africa',
  },
  {
    name: 'Benin',
    capital: 'Porto-Novo',
    currency: 'XOF',
    currencySymbol: 'Fr',
    population: 12123200,
    continent: 'Africa',
  },
  {
    name: 'Botswana',
    capital: 'Gaborone',
    currency: 'BWP',
    currencySymbol: 'P',
    population: 2351625,
    continent: 'Africa',
  },
  {
    name: 'Burkina Faso',
    capital: 'Ouagadougou',
    currency: 'XOF',
    currencySymbol: 'Fr',
    population: 20903278,
    continent: 'Africa',
  },
  {
    name: 'Burundi',
    capital: 'Gitega',
    currency: 'BIF',
    currencySymbol: 'Fr',
    population: 11890784,
    continent: 'Africa',
  },
  {
    name: 'Cabo Verde',
    capital: 'Praia',
    currency: 'CVE',
    currencySymbol: 'Esc',
    population: 555987,
    continent: 'Africa',
  },
  {
    name: 'Cameroon',
    capital: 'Yaoundé',
    currency: 'XAF',
    currencySymbol: 'Fr',
    population: 26545863,
    continent: 'Africa',
  },
  {
    name: 'Central African Republic',
    capital: 'Bangui',
    currency: 'XAF',
    currencySymbol: 'Fr',
    population: 4829767,
    continent: 'Africa',
  },
  {
    name: 'Chad',
    capital: "N'Djamena",
    currency: 'XAF',
    currencySymbol: 'Fr',
    population: 16425864,
    continent: 'Africa',
  },
  {
    name: 'Comoros',
    capital: 'Moroni',
    currency: 'KMF',
    currencySymbol: 'Fr',
    population: 869601,
    continent: 'Africa',
  },
  {
    name: 'Congo, Democratic Republic of the',
    capital: 'Kinshasa',
    currency: 'CDF',
    currencySymbol: 'Fr',
    population: 89561403,
    continent: 'Africa',
  },
  {
    name: 'Congo, Republic of the',
    capital: 'Brazzaville',
    currency: 'XAF',
    currencySymbol: 'Fr',
    population: 5518087,
    continent: 'Africa',
  },
  {
    name: 'Djibouti',
    capital: 'Djibouti',
    currency: 'DJF',
    currencySymbol: 'Fr',
    population: 988000,
    continent: 'Africa',
  },
  {
    name: 'Egypt',
    capital: 'Cairo',
    currency: 'EGP',
    currencySymbol: '£',
    population: 102334404,
    continent: 'Africa',
  },
  {
    name: 'Equatorial Guinea',
    capital: 'Malabo',
    currency: 'XAF',
    currencySymbol: 'Fr',
    population: 1402985,
    continent: 'Africa',
  },
  {
    name: 'Eritrea',
    capital: 'Asmara',
    currency: 'ERN',
    currencySymbol: 'Nfk',
    population: 3546437,
    continent: 'Africa',
  },
  {
    name: 'Eswatini',
    capital: 'Mbabane',
    currency: 'SZL',
    currencySymbol: 'E',
    population: 1160164,
    continent: 'Africa',
  },
  {
    name: 'Ethiopia',
    capital: 'Addis Ababa',
    currency: 'ETB',
    currencySymbol: 'Br',
    population: 114963588,
    continent: 'Africa',
  },
  {
    name: 'Gabon',
    capital: 'Libreville',
    currency: 'XAF',
    currencySymbol: 'Fr',
    population: 2225734,
    continent: 'Africa',
  },
  {
    name: 'Gambia',
    capital: 'Banjul',
    currency: 'GMD',
    currencySymbol: 'D',
    population: 2416668,
    continent: 'Africa',
  },
  {
    name: 'Ghana',
    capital: 'Accra',
    currency: 'GHS',
    currencySymbol: '₵',
    population: 31072940,
    continent: 'Africa',
  },
  {
    name: 'Guinea',
    capital: 'Conakry',
    currency: 'GNF',
    currencySymbol: 'Fr',
    population: 13132795,
    continent: 'Africa',
  },
  {
    name: 'Guinea-Bissau',
    capital: 'Bissau',
    currency: 'XOF',
    currencySymbol: 'Fr',
    population: 1968001,
    continent: 'Africa',
  },
  {
    name: 'Ivory Coast',
    capital: 'Yamoussoukro',
    currency: 'XOF',
    currencySymbol: 'Fr',
    population: 26378274,
    continent: 'Africa',
  },
  {
    name: 'Kenya',
    capital: 'Nairobi',
    currency: 'KES',
    currencySymbol: 'Sh',
    population: 53771296,
    continent: 'Africa',
  },
  {
    name: 'Lesotho',
    capital: 'Maseru',
    currency: 'LSL',
    currencySymbol: 'L',
    population: 2142249,
    continent: 'Africa',
  },
  {
    name: 'Liberia',
    capital: 'Monrovia',
    currency: 'LRD',
    currencySymbol: '$',
    population: 5057681,
    continent: 'Africa',
  },
  {
    name: 'Libya',
    capital: 'Tripoli',
    currency: 'LYD',
    currencySymbol: 'ل.د',
    population: 6871292,
    continent: 'Africa',
  },
  {
    name: 'Madagascar',
    capital: 'Antananarivo',
    currency: 'MGA',
    currencySymbol: 'Ar',
    population: 27691018,
    continent: 'Africa',
  },
  {
    name: 'Malawi',
    capital: 'Lilongwe',
    currency: 'MWK',
    currencySymbol: 'MK',
    population: 19129952,
    continent: 'Africa',
  },
  {
    name: 'Mali',
    capital: 'Bamako',
    currency: 'XOF',
    currencySymbol: 'Fr',
    population: 20250833,
    continent: 'Africa',
  },
  {
    name: 'Mauritania',
    capital: 'Nouakchott',
    currency: 'MRU',
    currencySymbol: 'UM',
    population: 4649658,
    continent: 'Africa',
  },
  {
    name: 'Mauritius',
    capital: 'Port Louis',
    currency: 'MUR',
    currencySymbol: '₨',
    population: 1271768,
    continent: 'Africa',
  },
  {
    name: 'Morocco',
    capital: 'Rabat',
    currency: 'MAD',
    currencySymbol: 'د.م.',
    population: 36910560,
    continent: 'Africa',
  },
  {
    name: 'Mozambique',
    capital: 'Maputo',
    currency: 'MZN',
    currencySymbol: 'MT',
    population: 31255435,
    continent: 'Africa',
  },
  {
    name: 'Namibia',
    capital: 'Windhoek',
    currency: 'NAD',
    currencySymbol: 'N$',
    population: 2540905,
    continent: 'Africa',
  },
  {
    name: 'Niger',
    capital: 'Niamey',
    currency: 'XOF',
    currencySymbol: 'Fr',
    population: 24206644,
    continent: 'Africa',
  },
  {
    name: 'Nigeria',
    capital: 'Abuja',
    currency: 'NGN',
    currencySymbol: '₦',
    population: 206139589,
    continent: 'Africa',
  },
  {
    name: 'Rwanda',
    capital: 'Kigali',
    currency: 'RWF',
    currencySymbol: 'Fr',
    population: 12952218,
    continent: 'Africa',
  },
  {
    name: 'Sao Tome and Principe',
    capital: 'São Tomé',
    currency: 'STN',
    currencySymbol: 'Db',
    population: 219159,
    continent: 'Africa',
  },
  {
    name: 'Senegal',
    capital: 'Dakar',
    currency: 'XOF',
    currencySymbol: 'Fr',
    population: 16743927,
    continent: 'Africa',
  },
  {
    name: 'Seychelles',
    capital: 'Victoria',
    currency: 'SCR',
    currencySymbol: '₨',
    population: 98347,
    continent: 'Africa',
  },
  {
    name: 'Sierra Leone',
    capital: 'Freetown',
    currency: 'SLL',
    currencySymbol: 'Le',
    population: 7976983,
    continent: 'Africa',
  },
  {
    name: 'Somalia',
    capital: 'Mogadishu',
    currency: 'SOS',
    currencySymbol: 'Sh',
    population: 15893222,
    continent: 'Africa',
  },
  {
    name: 'South Africa',
    capital: 'Pretoria',
    currency: 'ZAR',
    currencySymbol: 'R',
    population: 59308690,
    continent: 'Africa',
  },
  {
    name: 'South Sudan',
    capital: 'Juba',
    currency: 'SSP',
    currencySymbol: '£',
    population: 11193725,
    continent: 'Africa',
  },
  {
    name: 'Sudan',
    capital: 'Khartoum',
    currency: 'SDG',
    currencySymbol: 'ج.س.',
    population: 43849260,
    continent: 'Africa',
  },
  {
    name: 'Tanzania',
    capital: 'Dodoma',
    currency: 'TZS',
    currencySymbol: 'Sh',
    population: 59734218,
    continent: 'Africa',
  },
  {
    name: 'Togo',
    capital: 'Lomé',
    currency: 'XOF',
    currencySymbol: 'Fr',
    population: 8278724,
    continent: 'Africa',
  },
  {
    name: 'Tunisia',
    capital: 'Tunis',
    currency: 'TND',
    currencySymbol: 'د.ت',
    population: 11818619,
    continent: 'Africa',
  },
  {
    name: 'Uganda',
    capital: 'Kampala',
    currency: 'UGX',
    currencySymbol: 'Sh',
    population: 45741007,
    continent: 'Africa',
  },
  {
    name: 'Zambia',
    capital: 'Lusaka',
    currency: 'ZMW',
    currencySymbol: 'ZK',
    population: 18383955,
    continent: 'Africa',
  },
  {
    name: 'Zimbabwe',
    capital: 'Harare',
    currency: 'ZWL',
    currencySymbol: '$',
    population: 14862924,
    continent: 'Africa',
  },

  {
    name: 'Afghanistan',
    capital: 'Kabul',
    currency: 'AFN',
    currencySymbol: '؋',
    population: 38928346,
    continent: 'Asia',
  },
  {
    name: 'Armenia',
    capital: 'Yerevan',
    currency: 'AMD',
    currencySymbol: '֏',
    population: 2963243,
    continent: 'Asia',
  },
  {
    name: 'Azerbaijan',
    capital: 'Baku',
    currency: 'AZN',
    currencySymbol: '₼',
    population: 10139177,
    continent: 'Asia',
  },
  {
    name: 'Bahrain',
    capital: 'Manama',
    currency: 'BHD',
    currencySymbol: '.د.ب',
    population: 1701575,
    continent: 'Asia',
  },
  {
    name: 'Bangladesh',
    capital: 'Dhaka',
    currency: 'BDT',
    currencySymbol: '৳',
    population: 164689383,
    continent: 'Asia',
  },
  {
    name: 'Bhutan',
    capital: 'Thimphu',
    currency: 'BTN',
    currencySymbol: 'Nu.',
    population: 771608,
    continent: 'Asia',
  },
  {
    name: 'Brunei',
    capital: 'Bandar Seri Begawan',
    currency: 'BND',
    currencySymbol: '$',
    population: 437479,
    continent: 'Asia',
  },
  {
    name: 'Cambodia',
    capital: 'Phnom Penh',
    currency: 'KHR',
    currencySymbol: '៛',
    population: 16718965,
    continent: 'Asia',
  },
  {
    name: 'China',
    capital: 'Beijing',
    currency: 'CNY',
    currencySymbol: '¥',
    population: 1444216107,
    continent: 'Asia',
  },
  {
    name: 'Cyprus',
    capital: 'Nicosia',
    currency: 'EUR',
    currencySymbol: '€',
    population: 1207359,
    continent: 'Asia',
  },
  {
    name: 'Georgia',
    capital: 'Tbilisi',
    currency: 'GEL',
    currencySymbol: '₾',
    population: 3716858,
    continent: 'Asia',
  },
  {
    name: 'India',
    capital: 'New Delhi',
    currency: 'INR',
    currencySymbol: '₹',
    population: 1393409038,
    continent: 'Asia',
  },
  {
    name: 'Indonesia',
    capital: 'Jakarta',
    currency: 'IDR',
    currencySymbol: 'Rp',
    population: 273523615,
    continent: 'Asia',
  },
  {
    name: 'Iran',
    capital: 'Tehran',
    currency: 'IRR',
    currencySymbol: '﷼',
    population: 83992949,
    continent: 'Asia',
  },
  {
    name: 'Iraq',
    capital: 'Baghdad',
    currency: 'IQD',
    currencySymbol: 'ع.د',
    population: 40222493,
    continent: 'Asia',
  },
  {
    name: 'Israel',
    capital: 'Jerusalem',
    currency: 'ILS',
    currencySymbol: '₪',
    population: 8655535,
    continent: 'Asia',
  },
  {
    name: 'Japan',
    capital: 'Tokyo',
    currency: 'JPY',
    currencySymbol: '¥',
    population: 126476461,
    continent: 'Asia',
  },
  {
    name: 'Jordan',
    capital: 'Amman',
    currency: 'JOD',
    currencySymbol: 'د.ا',
    population: 10203134,
    continent: 'Asia',
  },
  {
    name: 'Kazakhstan',
    capital: 'Nur-Sultan',
    currency: 'KZT',
    currencySymbol: '₸',
    population: 18754440,
    continent: 'Asia',
  },
  {
    name: 'Kuwait',
    capital: 'Kuwait City',
    currency: 'KWD',
    currencySymbol: 'د.ك',
    population: 4270571,
    continent: 'Asia',
  },
  {
    name: 'Kyrgyzstan',
    capital: 'Bishkek',
    currency: 'KGS',
    currencySymbol: 'лв',
    population: 6524195,
    continent: 'Asia',
  },
  {
    name: 'Laos',
    capital: 'Vientiane',
    currency: 'LAK',
    currencySymbol: '₭',
    population: 7275560,
    continent: 'Asia',
  },
  {
    name: 'Lebanon',
    capital: 'Beirut',
    currency: 'LBP',
    currencySymbol: 'ل.ل',
    population: 6825445,
    continent: 'Asia',
  },
  {
    name: 'Malaysia',
    capital: 'Kuala Lumpur',
    currency: 'MYR',
    currencySymbol: 'RM',
    population: 32365999,
    continent: 'Asia',
  },
  {
    name: 'Maldives',
    capital: 'Malé',
    currency: 'MVR',
    currencySymbol: '.ރ',
    population: 540542,
    continent: 'Asia',
  },
  {
    name: 'Mongolia',
    capital: 'Ulaanbaatar',
    currency: 'MNT',
    currencySymbol: '₮',
    population: 3278290,
    continent: 'Asia',
  },
  {
    name: 'Myanmar',
    capital: 'Naypyidaw',
    currency: 'MMK',
    currencySymbol: 'K',
    population: 54409800,
    continent: 'Asia',
  },
  {
    name: 'Nepal',
    capital: 'Kathmandu',
    currency: 'NPR',
    currencySymbol: '₨',
    population: 29136808,
    continent: 'Asia',
  },
  {
    name: 'North Korea',
    capital: 'Pyongyang',
    currency: 'KPW',
    currencySymbol: '₩',
    population: 25778816,
    continent: 'Asia',
  },
  {
    name: 'Oman',
    capital: 'Muscat',
    currency: 'OMR',
    currencySymbol: 'ر.ع.',
    population: 5106626,
    continent: 'Asia',
  },
  {
    name: 'Pakistan',
    capital: 'Islamabad',
    currency: 'PKR',
    currencySymbol: '₨',
    population: 220892340,
    continent: 'Asia',
  },
  {
    name: 'Palestine',
    capital: 'Ramallah',
    currency: 'ILS',
    currencySymbol: '₪',
    population: 5101414,
    continent: 'Asia',
  },
  {
    name: 'Philippines',
    capital: 'Manila',
    currency: 'PHP',
    currencySymbol: '₱',
    population: 109581078,
    continent: 'Asia',
  },
  {
    name: 'Qatar',
    capital: 'Doha',
    currency: 'QAR',
    currencySymbol: 'ر.ق',
    population: 2881060,
    continent: 'Asia',
  },
  {
    name: 'Russia',
    capital: 'Moscow',
    currency: 'RUB',
    currencySymbol: '₽',
    population: 145912025,
    continent: 'Asia',
  },
  {
    name: 'Saudi Arabia',
    capital: 'Riyadh',
    currency: 'SAR',
    currencySymbol: 'ر.س',
    population: 34813871,
    continent: 'Asia',
  },
  {
    name: 'Singapore',
    capital: 'Singapore',
    currency: 'SGD',
    currencySymbol: '$',
    population: 5850342,
    continent: 'Asia',
  },
  {
    name: 'South Korea',
    capital: 'Seoul',
    currency: 'KRW',
    currencySymbol: '₩',
    population: 51269185,
    continent: 'Asia',
  },
  {
    name: 'Sri Lanka',
    capital: 'Sri Jayawardenepura Kotte',
    currency: 'LKR',
    currencySymbol: 'Rs',
    population: 21413249,
    continent: 'Asia',
  },
  {
    name: 'Syria',
    capital: 'Damascus',
    currency: 'SYP',
    currencySymbol: '£',
    population: 17500658,
    continent: 'Asia',
  },
  {
    name: 'Taiwan',
    capital: 'Taipei',
    currency: 'TWD',
    currencySymbol: 'NT$',
    population: 23816775,
    continent: 'Asia',
  },
  {
    name: 'Tajikistan',
    capital: 'Dushanbe',
    currency: 'TJS',
    currencySymbol: 'ЅМ',
    population: 9537645,
    continent: 'Asia',
  },
  {
    name: 'Thailand',
    capital: 'Bangkok',
    currency: 'THB',
    currencySymbol: '฿',
    population: 69799978,
    continent: 'Asia',
  },
  {
    name: 'Timor-Leste',
    capital: 'Dili',
    currency: 'USD',
    currencySymbol: '$',
    population: 1318445,
    continent: 'Asia',
  },
  {
    name: 'Turkmenistan',
    capital: 'Ashgabat',
    currency: 'TMT',
    currencySymbol: 'm',
    population: 6031200,
    continent: 'Asia',
  },
  {
    name: 'United Arab Emirates',
    capital: 'Abu Dhabi',
    currency: 'AED',
    currencySymbol: 'د.إ',
    population: 9890402,
    continent: 'Asia',
  },
  {
    name: 'Uzbekistan',
    capital: 'Tashkent',
    currency: 'UZS',
    currencySymbol: 'лв',
    population: 33469203,
    continent: 'Asia',
  },
  {
    name: 'Vietnam',
    capital: 'Hanoi',
    currency: 'VND',
    currencySymbol: '₫',
    population: 97338579,
    continent: 'Asia',
  },
  {
    name: 'Yemen',
    capital: "Sana'a",
    currency: 'YER',
    currencySymbol: '﷼',
    population: 29825964,
    continent: 'Asia',
  },
  {
    name: 'Australia',
    capital: 'Canberra',
    currency: 'AUD',
    currencySymbol: '$',
    population: 25687041,
    continent: 'Oceania',
  },
  {
    name: 'Fiji',
    capital: 'Suva',
    currency: 'FJD',
    currencySymbol: '$',
    population: 896444,
    continent: 'Oceania',
  },
  {
    name: 'Kiribati',
    capital: 'Tarawa',
    currency: 'AUD',
    currencySymbol: '$',
    population: 119446,
    continent: 'Oceania',
  },
  {
    name: 'Marshall Islands',
    capital: 'Majuro',
    currency: 'USD',
    currencySymbol: '$',
    population: 59194,
    continent: 'Oceania',
  },
  {
    name: 'Micronesia',
    capital: 'Palikir',
    currency: 'USD',
    currencySymbol: '$',
    population: 115023,
    continent: 'Oceania',
  },
  {
    name: 'Nauru',
    capital: 'Yaren',
    currency: 'AUD',
    currencySymbol: '$',
    population: 10834,
    continent: 'Oceania',
  },
  {
    name: 'New Zealand',
    capital: 'Wellington',
    currency: 'NZD',
    currencySymbol: '$',
    population: 5084300,
    continent: 'Oceania',
  },
  {
    name: 'Palau',
    capital: 'Ngerulmud',
    currency: 'USD',
    currencySymbol: '$',
    population: 18094,
    continent: 'Oceania',
  },
  {
    name: 'Papua New Guinea',
    capital: 'Port Moresby',
    currency: 'PGK',
    currencySymbol: 'K',
    population: 8947027,
    continent: 'Oceania',
  },
  {
    name: 'Samoa',
    capital: 'Apia',
    currency: 'WST',
    currencySymbol: 'T',
    population: 198414,
    continent: 'Oceania',
  },
  {
    name: 'Solomon Islands',
    capital: 'Honiara',
    currency: 'SBD',
    currencySymbol: '$',
    population: 686878,
    continent: 'Oceania',
  },
  {
    name: 'Tonga',
    capital: 'Nukuʻalofa',
    currency: 'TOP',
    currencySymbol: 'T$',
    population: 105695,
    continent: 'Oceania',
  },
  {
    name: 'Tuvalu',
    capital: 'Funafuti',
    currency: 'AUD',
    currencySymbol: '$',
    population: 11792,
    continent: 'Oceania',
  },
  {
    name: 'Vanuatu',
    capital: 'Port Vila',
    currency: 'VUV',
    currencySymbol: 'Vt',
    population: 307145,
    continent: 'Oceania',
  },
  {
    name: 'Antigua and Barbuda',
    capital: "St. John's",
    currency: 'XCD',
    currencySymbol: '$',
    population: 97928,
    continent: 'Americas',
  },
  {
    name: 'Argentina',
    capital: 'Buenos Aires',
    currency: 'ARS',
    currencySymbol: '$',
    population: 45195774,
    continent: 'Americas',
  },
  {
    name: 'Bahamas',
    capital: 'Nassau',
    currency: 'BSD',
    currencySymbol: '$',
    population: 393244,
    continent: 'Americas',
  },
  {
    name: 'Barbados',
    capital: 'Bridgetown',
    currency: 'BBD',
    currencySymbol: '$',
    population: 287371,
    continent: 'Americas',
  },
  {
    name: 'Belize',
    capital: 'Belmopan',
    currency: 'BZD',
    currencySymbol: '$',
    population: 397621,
    continent: 'Americas',
  },
  {
    name: 'Bolivia',
    capital: 'Sucre',
    currency: 'BOB',
    currencySymbol: 'Bs.',
    population: 11673021,
    continent: 'Americas',
  },
  {
    name: 'Brazil',
    capital: 'Brasília',
    currency: 'BRL',
    currencySymbol: 'R$',
    population: 212559417,
    continent: 'Americas',
  },
  {
    name: 'Canada',
    capital: 'Ottawa',
    currency: 'CAD',
    currencySymbol: '$',
    population: 38005238,
    continent: 'Americas',
  },
  {
    name: 'Chile',
    capital: 'Santiago',
    currency: 'CLP',
    currencySymbol: '$',
    population: 19116201,
    continent: 'Americas',
  },
  {
    name: 'Colombia',
    capital: 'Bogotá',
    currency: 'COP',
    currencySymbol: '$',
    population: 50882891,
    continent: 'Americas',
  },
  {
    name: 'Costa Rica',
    capital: 'San José',
    currency: 'CRC',
    currencySymbol: '₡',
    population: 5094118,
    continent: 'Americas',
  },
  {
    name: 'Cuba',
    capital: 'Havana',
    currency: 'CUP',
    currencySymbol: '₱',
    population: 11326616,
    continent: 'Americas',
  },
  {
    name: 'Dominica',
    capital: 'Roseau',
    currency: 'XCD',
    currencySymbol: '$',
    population: 71991,
    continent: 'Americas',
  },
  {
    name: 'Dominican Republic',
    capital: 'Santo Domingo',
    currency: 'DOP',
    currencySymbol: 'RD$',
    population: 10847904,
    continent: 'Americas',
  },
  {
    name: 'Ecuador',
    capital: 'Quito',
    currency: 'USD',
    currencySymbol: '$',
    population: 17643054,
    continent: 'Americas',
  },
  {
    name: 'El Salvador',
    capital: 'San Salvador',
    currency: 'USD',
    currencySymbol: '$',
    population: 6486201,
    continent: 'Americas',
  },
  {
    name: 'Grenada',
    capital: "St. George's",
    currency: 'XCD',
    currencySymbol: '$',
    population: 112523,
    continent: 'Americas',
  },
  {
    name: 'Guatemala',
    capital: 'Guatemala City',
    currency: 'GTQ',
    currencySymbol: 'Q',
    population: 17915568,
    continent: 'Americas',
  },
  {
    name: 'Guyana',
    capital: 'Georgetown',
    currency: 'GYD',
    currencySymbol: '$',
    population: 786552,
    continent: 'Americas',
  },
  {
    name: 'Haiti',
    capital: 'Port-au-Prince',
    currency: 'HTG',
    currencySymbol: 'G',
    population: 11402528,
    continent: 'Americas',
  },
  {
    name: 'Honduras',
    capital: 'Tegucigalpa',
    currency: 'HNL',
    currencySymbol: 'L',
    population: 9904607,
    continent: 'Americas',
  },
  {
    name: 'Jamaica',
    capital: 'Kingston',
    currency: 'JMD',
    currencySymbol: 'J$',
    population: 2961167,
    continent: 'Americas',
  },
  {
    name: 'Mexico',
    capital: 'Mexico City',
    currency: 'MXN',
    currencySymbol: '$',
    population: 128932753,
    continent: 'Americas',
  },
  {
    name: 'Nicaragua',
    capital: 'Managua',
    currency: 'NIO',
    currencySymbol: 'C$',
    population: 6624554,
    continent: 'Americas',
  },
  {
    name: 'Panama',
    capital: 'Panama City',
    currency: 'PAB',
    currencySymbol: 'B/.',
    population: 4314768,
    continent: 'Americas',
  },
  {
    name: 'Paraguay',
    capital: 'Asunción',
    currency: 'PYG',
    currencySymbol: '₲',
    population: 7132538,
    continent: 'Americas',
  },
  {
    name: 'Peru',
    capital: 'Lima',
    currency: 'PEN',
    currencySymbol: 'S/.',
    population: 32971854,
    continent: 'Americas',
  },
  {
    name: 'Saint Kitts and Nevis',
    capital: 'Basseterre',
    currency: 'XCD',
    currencySymbol: '$',
    population: 53199,
    continent: 'Americas',
  },
  {
    name: 'Saint Lucia',
    capital: 'Castries',
    currency: 'XCD',
    currencySymbol: '$',
    population: 184400,
    continent: 'Americas',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    capital: 'Kingstown',
    currency: 'XCD',
    currencySymbol: '$',
    population: 110947,
    continent: 'Americas',
  },
  {
    name: 'Suriname',
    capital: 'Paramaribo',
    currency: 'SRD',
    currencySymbol: '$',
    population: 586632,
    continent: 'Americas',
  },
  {
    name: 'Trinidad and Tobago',
    capital: 'Port of Spain',
    currency: 'TTD',
    currencySymbol: '$',
    population: 1399488,
    continent: 'Americas',
  },
  {
    name: 'United States',
    capital: 'Washington, D.C.',
    currency: 'USD',
    currencySymbol: '$',
    population: 331002651,
    continent: 'Americas',
  },
  {
    name: 'Uruguay',
    capital: 'Montevideo',
    currency: 'UYU',
    currencySymbol: '$',
    population: 3473730,
    continent: 'Americas',
  },
  {
    name: 'Venezuela',
    capital: 'Caracas',
    currency: 'VES',
    currencySymbol: 'Bs.',
    population: 28435940,
    continent: 'Americas',
  },
];
